### ISSUE TITLE
Enlive template reloading seems not to work on Windows

### ISSUE THREAD

**Issue by sveri** [cgrand/enlive#92]
Hi, like the title says I cannot get enlive template reloading running. I provided a small example here: https://github.com/sveri/enlive_http_kit

I created that project with luminus: lein new luminus projectname +http-kit and run it with lein run -dev.

The relevant files are base.html and home.clj

**Comment by jdf-id-au** [comment]
I was unable to get it working on the Mac either, and unfortunately couldn't get [akolov's solution](https://github.com/kolov/enlive-reload) working either (doubtless because of my own lack of skill). [He describes](http://kolov-it.com/automatic-reloading-enlive-templates/) the nature of the underlying Mac problem.

**Comment by skprasadu** [comment]
This issue was impacting https://github.com/plexus/chestnut lein template. 

The issue has been fixed, I tested it and it works. For slightly adventurous and impatient souls, get the latest enlive code in your machine and "lein install" it.. it is still not in clojars. The code snipped that fixed this is in src/net/cgrand/reload.clj as below. 

(defmethod watch-url "file" [^java.net.URL url ns]
  (let [path (java.nio.file.Paths/get (.toURI url))
        ws (watch-service ns)]
    (ws path)))

**Comment by plexus** [comment]
@cgrand would you consider a new release of Enlive? If I'm not mistaken the current one is over a year old, and seems a number of fixes have gone in since then.

**Comment by conan** [comment]
I've had success checking out and `lein install`ing enlive to fix this issue, as it prevents [chestnut](https://github.com/plexus/chestnut/issues/104) project REPLs from working on windows.  A Clojars release would be much appreciated.

**Comment by vojd** [comment]
:+1: on a new Enlive release. Having the same issue on Windows.

**Comment by acron0** [comment]
+1 on a new Enlive release to fix this. Thanks!

**Comment by justiniac** [comment]
Fixed, clojars incoming.
Thankies!
